### ISSUE TITLE
NPCDestinations loading after BetonQuest causing location based conditions to not register

### ISSUE THREAD

**Issue by Aeneas1022** [Nutty101/NPC_Destinations2#10] opened 2017-11-30 02:53 UTC
At the title states I am having issues with the load order of NPCDestinations and BetonQuest. I noticed this after restarting my server the other day and then trying to talk to one of my NPCs "Rika" at a graveyard where she is supposed to inform the player of a loved one having passed away in a wolf attack (which triggers a whole questline). Instead she did nothing but the whole 
===Conversation with Rika Started====
===Conversation with Rika Ended====
as if the quest was incorrect. I then reloaded NPCDestinations after looking through the quest and the quest worked fine. I tried manually adding in the plugin.yml of BetonQuest.
loadafter: [NPCDestinations]
&
loadbefore: [BetonQuest]
in the plugin.yml of NPCDestinations, but either my server would stop recognizing the plugins entirely ( at one point Beton just stopped working and went red on my plugins list) or the Animations add-on to NPCDestinations would stop working eliminating some of my quests that require the NPC to be sitting in a certain spot or laying down in a bed. I went ahead and posted a similar post in Co0sh's BetonQuest GitHub, but I figured to be safe I should add this one in here in case he isn't able to check it soon. Thanks for reading and any replies in advance!
-Aen

**Comment by MWFIAE** [comment] 2017-11-30 17:07
Also here is the issue that was created in the betonquest repo:
https://github.com/Co0sh/BetonQuest/issues/674

Doing some crosslinking so that everyone can stay updated without doing to much search :)

**Comment by Nutty101** [comment] 2017-12-01 02:28
yeah, at the moment i am away from my main desktop with very limited access. the issue is that i used to wait for the server to finish loading and attach to betonquest. he's changed some things thatbare causing this now in the newer builds.  i did a test to get it at the time of onenable, but that breaks old versions. so i need to build some stuff to ensure i dont break people on past versions. i also dont know that the order is 100% perfect as in testing ive loaded before beton was ready. some fidgiting to get the timing right. i will get it, but i'm busy with my house in colorado trying to sell it. once done, this will be resolved one way or another.

**Comment by Aeneas1022** [comment] 2017-12-01 04:41
that's alright I totally understand and I appreciate the response. Good luck on selling the house. Thanks MWFIAE for linking those two issues earlier.

**Comment by Nutty101** [comment] 2017-12-03 01:44
Fixed in 2.1.16.  Had to add a version check for BetonQuest and act accordingly to the version you are running. Otherwise, I break the old, or the new. No happy mediums on this one.

**Closed by Nutty101** 2017-12-03 01:44 UTC
